alias e=emacs
alias g=git
alias ls='ls -G'
alias la='ls -alt'
alias ll='ls -lt'
alias dev='cd ~/dev'
alias py=python
alias rerc='source ~/.bash_profile'
alias mci='mvn clean install'
alias mcis='mci -DskipTests'
alias v=vagrant
