;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-visual-line
        cider-eval-last-sexp
        downcase-region
        electric-newline-and-maybe-indent
        end-of-visual-line
        indent-for-tab-command
        kill-visual-line
        markdown-insert-list-item
        sp-backward-unwrap-sexp
        sp-forward-barf-sexp
        sp-forward-slurp-sexp
        upcase-region
        ))

(setq mc/cmds-to-run-once
      '(
        help-for-help
        ))
