;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	beginning-of-visual-line
	cider-eval-last-sexp
	electric-newline-and-maybe-indent
	end-of-visual-line
	indent-for-tab-command
	kill-visual-line
	sp-backward-unwrap-sexp
	))

(setq mc/cmds-to-run-once
      '(
	))
